theme: jekyll-theme-hacker
title: prof.apokalips
email: 
description: >- # this means to ignore newlines until "baseurl:"
  Foreseen The Foretold.
baseurl: "/prof.apokalips" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: aliferfan_
github_username: Ap0K4L1p5

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: prof.apokalips
